import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import './MenuPreview.css';
import { AllergenLabels, DietaryTypeIcons, DietaryTypeLabels, NutritionTagLabels } from '@/shared/types/menu.types';
export const MenuPreview = ({ formData, categories, selectedAllergens, selectedNutritionTags, }) => {
    const selectedCategory = categories.find((c) => c._id === formData.categoryId);
    return (_jsxs("div", { className: "preview-card", children: [_jsx("h3", { className: "preview-title", children: "Preview" }), _jsxs("div", { className: "menuitem-preview", children: [formData.image && (_jsx("div", { className: "preview-image-container", children: _jsx("img", { src: formData.image, alt: "Menu item preview", className: "preview-image", onError: (e) => {
                                e.target.style.display = 'none';
                            } }) })), _jsxs("div", { className: "preview-content", children: [_jsxs("div", { className: "preview-header", children: [_jsx("h4", { className: "preview-item-name", children: formData.name || 'Menu Item Name' }), _jsx("span", { className: `preview-availability ${formData.isAvailable ? 'available' : 'unavailable'}`, children: formData.isAvailable ? 'Available' : 'Unavailable' })] }), _jsx("p", { className: "preview-description", children: formData.description || 'Menu item description will appear here' }), selectedCategory && (_jsx("span", { className: "preview-category", children: selectedCategory.name })), formData.itemType === 'food' && formData.dietaryType && (_jsxs("span", { className: "preview-dietary", children: [DietaryTypeIcons[formData.dietaryType], ' ', DietaryTypeLabels[formData.dietaryType]] })), formData.preparationTime && (_jsxs("span", { className: "preview-prep-time", children: ["\u23F1\uFE0F ", formData.preparationTime, " min"] })), formData.itemType === 'food' && formData.spiceLevel && (_jsxs("span", { className: "preview-spice", children: ["\uD83C\uDF36\uFE0F ", formData.spiceLevel] })), _jsx("div", { className: "preview-pricing", children: formData.discountPrice ? (_jsxs(_Fragment, { children: [_jsxs("span", { className: "preview-original-price", children: ["$", formData.price || '0.00'] }), _jsxs("span", { className: "preview-discount-price", children: ["$", formData.discountPrice || '0.00'] })] })) : (_jsxs("span", { className: "preview-current-price", children: ["$", formData.price || '0.00'] })) }), selectedAllergens.length > 0 && (_jsxs("div", { className: "preview-section", children: [_jsx("p", { className: "preview-section-title", children: "Allergens:" }), _jsx("div", { className: "preview-tags", children: selectedAllergens.map((allergen) => (_jsx("span", { className: "preview-tag allergen-tag", children: AllergenLabels[allergen] }, allergen))) })] })), selectedNutritionTags.length > 0 && (_jsxs("div", { className: "preview-section", children: [_jsx("p", { className: "preview-section-title", children: "Nutrition:" }), _jsx("div", { className: "preview-tags", children: selectedNutritionTags.map((tag) => (_jsx("span", { className: "preview-tag nutrition-tag", children: NutritionTagLabels[tag] }, tag))) })] })), formData.tags && (_jsx("div", { className: "preview-tags", children: formData.tags.split(',').map((tag, idx) => (_jsx("span", { className: "preview-tag", children: tag.trim() }, idx))) }))] })] })] }));
};
